POSTGRES_SCHEMA: app_schema_users_service

server:
  port: ${SERVER_PORT:8091}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:another-service}
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/justanotherapp}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:2810}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: ${POSTGRES_SCHEMA}
        # ✅ Fixed: dialect goes here, not under spring.jpa.hibernate
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: false

  kafka:
    bootstrap-servers: localhost:9092 # where your Kafka broker will run (Docker)
    consumer:
      group-id: justanotherapp-group
      auto-offset-reset: earliest # read from beginning if no offset exists
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
